name: Reusable workflow to build Android applications

on:
  workflow_call:
      inputs:
        scout_checkout_ref:
          description: 'A branch, tag or SHA to checkout the code'
          required: true
          type: string
        scout_build_name:
          description: 'An optional string to describe the build'          
          required: false
          type: string
          default: 'Build'
      outputs:
        scout_artifact_name:
          description: 'The file name of the generated artifact'
          value: ${{ jobs.build-job.outputs.artifact_name }}

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      artifact_name: ${{ steps.generate_artifact_names.outputs.artifact_name }}
    steps:
    - name: Print inputs
      run: |
        echo "scout_checkout_ref=${{ inputs.scout_checkout_ref }}"
        echo "scout_build_name=${{ inputs.scout_build_name }}"
    - name: Print build environment
      run:
        env | sort      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.scout_checkout_ref }}
        fetch-depth: 0
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate version code
      run: ./generateVersionCode.sh
    - name: Build with Gradle
      run: ./gradlew clean assemble
    - name: Generate artifact names
      id: vars
      run: |
        echo "sha_long=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "full_ref=$(git describe --all)" >> $GITHUB_OUTPUT
        echo "version_code=$(cat versionCode.txt)" >> $GITHUB_OUTPUT
        echo "artifact_name=${{ inputs.scout_build_name }}.${{ version_code }}.$(date +'%Y%m%d-%H%M%S').$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.vars.outputs.artifact_name }}
        path: app/build/outputs/*
    - name: Find last successful build
      id: nx_set_shas
      uses: nrwl/nx-set-shas@v4        
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.2.0
      with:
        head-ref: ${{ steps.nx_set_shas.outputs.head }}
        base-ref: ${{ steps.nx_set_shas.outputs.base }}
        myToken: ${{ secrets.GITHUB_TOKEN }}
        fetch: false
    - name: Add build summary
      run: |
        echo "#### Version code: ${{ steps.vars.outputs.version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- Git Repository: https://github.com/${{ github.repository }}/tree/${{ steps.vars.outputs.sha_long }}  " >> $GITHUB_STEP_SUMMARY
        echo "- Git reference: ${{ steps.vars.outputs.full_ref }}  " >> $GITHUB_STEP_SUMMARY
        echo "#### Changelog since the last successful build" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.changelog.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY`