name: Reusable workflow to build Android applications

on:
  workflow_call:
      inputs:
        checkout_ref:
          description: 'A branch, tag or SHA to checkout the code'
          required: true
          type: string
        build_name:
          description: 'A string to describe the build'          
          required: false
          type: string
          default: 'Build'
        run_os:
          description: 'OS for this workflow'
          required: false
          type: string
          default: 'ubuntu-22.04'          
        java_ver:
          description: 'Java version to build Android applications'
          required: false
          type: string
          default: '17'
        java_dist:
          description: 'Java distribution to build Android applications'
          required: false
          type: string
          default: 'temurin'
      outputs:
        scout_artifact_name:
          description: 'The file name of the generated artifact'
          value: ${{ jobs.build-job.outputs.artifact_name }}
  
jobs:
  build-job:
    name: Build
    runs-on: ${{ inputs.run_os }}
    outputs:
      artifact_name: ${{ steps.generate_artifact_name.outputs.artifact_name }}
    steps:
    - name: Print inputs
      run: |
        run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Print build environment
      run:
        env | sort      
    - name: Checkout code from ${{ inputs.checkout_ref }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout_ref }}
        fetch-depth: 0
        submodules: true
    - name: Find last successful build
      id: nx_set_shas
      uses: nrwl/nx-set-shas@v4
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.2.0
      with:
        head-ref: ${{ steps.nx_set_shas.outputs.head }}
        base-ref: ${{ steps.nx_set_shas.outputs.base }}
        myToken: ${{ secrets.GITHUB_TOKEN }}
        fetch: false
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_ver }}
        distribution: ${{ inputs.java_dist }}
        cache: gradle
    - name: Generate version code
      run: |
        ./generateVersionCode.sh
        echo "scout_version_code=$(cat versionCode.txt)" >> $GITHUB_ENV
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assemble
    - name: Generate artifact name
      id: generate_artifact_name
      run: |
        echo "artifact_name=${{ inputs.build_name }}.${{ env.scout_version_code }}.$(date +'%Y%m%d-%H%M%S').$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.generate_artifact_name.outputs.artifact_name }}
        path: app/build/outputs/*
    - name: Add build summary
      run: |
        echo "#### ${{ inputs.build_name }} Version code: ${{ env.scout_version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- Git Repository: https://github.com/${{ github.repository }}/tree/$(git rev-parse HEAD)  " >> $GITHUB_STEP_SUMMARY
        echo "- Git reference: $(git describe --all)  " >> $GITHUB_STEP_SUMMARY
        echo "#### Changelog since the last successful build" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.changelog.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY
