name: Reusable workflow to create Android applications

on:
  workflow_call:
      inputs:
        scout_checkout_ref:
          description: 'A branch, tag or SHA to checkout the code'
          required: true
          type: string
        scout_build_name:
          description: 'An optional string to describe the build'          
          required: false
          type: string
          default: 'Build'
  
jobs:
  build_job:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Print build environment
      run:
        env | sort      
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.scout_checkout_ref }}
        fetch-depth: 0
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate version code
      run: ./generateVersionCode.sh
    - name: Set github variables
      run: | 
        echo "scout_build_datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "scout_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "scout_sha_long=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "scout_full_ref=$(git describe --all)" >> $GITHUB_ENV
        echo "scout_version_code=$(cat versionCode.txt)" >> $GITHUB_ENV
    - name: Build with Gradle
      run: ./gradlew clean assemble
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.scout_build_name }}.${{ env.scout_version_code }}.${{ env.scout_build_datetime }}.${{ env.scout_sha_short }}
        path: app/build/outputs/*
    - name: Find last successful build
      id: nx_set_shas
      uses: nrwl/nx-set-shas@v4        
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.2.0
      with:
        head-ref: ${{ steps.nx_set_shas.outputs.head }}
        base-ref: ${{ steps.nx_set_shas.outputs.base }}
        fetch: false
    - name: Add build summary
      run: |
        echo "#### Version code: ${{ env.scout_version_code }}" >> $GITHUB_STEP_SUMMARY
        echo "- Git Repository: https://github.com/${{ github.repository }}/tree/${{ env.scout_sha_long }}  " >> $GITHUB_STEP_SUMMARY
        echo "- Git reference: ${{ env.scout_full_ref }}  " >> $GITHUB_STEP_SUMMARY
        echo "#### Changelog since the last successful build" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.changelog.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY