name: Reusable workflow to archive artifact to S3

on:
  workflow_call:
      inputs:
        bucket_name:
          description: 'S3 bucket name (without /)'
          required: true
          type: string
        folder_name:
          description: 'S3 destination folder name (without /)'          
          required: true
          type: string
          default: ''
        artifact_name:
          description: 'The artifact name'
          required: true
          type: string
  
jobs:
  archive-job:
    name: Copy to S3
    runs-on: ubuntu-latest
    env:
      s3_path: ${{ inputs.bucket_name }}/${{ inputs.folder_name }}/
      file_name: ${{ inputs.artifact_name }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: ${{ env.file_name }}
      - name: Copy to S3
        run: |
          echo "aws s3 cp ${{ env.file_name }} ${{ env.s3_path }}"
      - name: Add build summary
        run: |
          echo "#### This build artifact is archived at [Amazon S3 Bucket (TODO)](${{ env.s3_path }}/${{ env.file_name }})" >> $GITHUB_STEP_SUMMARY
