name: Create Engineering Build

on:
  push:
    branches: 
      - 'main'

jobs:
  call-workflow:
    name: Create EngineeringBuild
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: main
      scout_build_name: EngineeringBuild
    secrets:
      scout_github_token: ${{ secrets.SCOUT_BUILD_TOKEN }}
