name: Create Engineering Build

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  call-workflow:
    name: Create EngineeringBuild
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: main
      scout_build_name: EngineeringBuild
    secrets:
      scout_github_token: ${{ secrets.GITHUB_TOKEN }}
