name: Generate Engineering Build

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build Name'
        required: false
        type: choice
        default: 'EngineeringBuild'
        options:
          - 'EngineeringBuild'
          - 'QaBuild'
      checkout_ref:
        description: 'Checkout branch, tag or SHA'
        required: false
        type: string
        default: 'main'

env:
  CHECKOUT_REF: 'main'
  BUILD_NAME: "EngineeringBuild"

jobs:
  init_vars_job:
    name: Initialize Variables
    runs-on: ubuntu-latest
    outputs:
      scout_checkout_ref: ${{ steps.vars_step.outputs.checkout_ref }}
      scout_build_name: ${{ steps.vars_step.outputs.build_name }}
    steps:
      - name: copy outputs
        id: vars_step
        run: |
          echo "checkout_ref=${{ inputs.checkout_ref || env.CHECKOUT_REF }} " >> $GITHUB_OUTPUT
          echo "build_name=${{ inputs.build_name || env.BUILD_NAME }}" >> $GITHUB_OUTPUT    
  call_workflow_job:
    needs: init_vars_job
    name: Generate ${{ needs.init_vars_job.outputs.scout_build_name }}
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: ${{ needs.init_vars_job.outputs.scout_checkout_ref }}
      scout_build_name: ${{ needs.init_vars_job.outputs.scout_build_name }}
  archive_artifact_job:
    needs: call_workflow_job
    name: Archive Artifacts
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ARTIFACT NAME: ${{ needs.call_workflow_job.outputs.scout_artifact_name }}"          
      - shell: bash
        run: |
          ls -l