name: Generate QA Build

on:
  workflow_dispatch:

jobs:
  call-workflow-job:
    name: Generate QaBuild
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: build/qa
      scout_build_name: QaBuild
