name: Generate Engineering Build

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: 'Checkout branch, tag or SHA'
        required: false
        type: string
        default: 'main'
      should_archive:
        description: 'Archive generated artifact'
        required: false
        type: boolean
        default: false

jobs:
  build_workflow_job:
    name: Generate
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      build_name: 'EngineeringBuild'
      checkout_ref: ${{ inputs.checkout_ref || 'main' }}
  archive_artifact_job:
    name: Archive
    needs:
      - call_workflow_job
    if: ${{ inputs.should_archive }}
    uses: ./.github/workflows/archive_s3-workflow.yml
    with:
      bucket_name: 's3://client-build-archives'
      folder_name: 'EngineeringBuild'
      artifact_name: ${{ needs.build_workflow_job.outputs.artifact_name }}
