name: Generate Engineering Build

on:
  push:
    branches: 
      - 'main'
    workflow_dispatch:

env:
  checkout_ref: main
  build_name: EngineeringBuild
  
jobs:
  init-vars-job:
    name: Initialize global variables
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "{{ env.checkout_ref }} " >> $GITHUB_ENV
          echo "{{ env.build_name }}" >> $GITHUB_ENV
    
  call-workflow-job:
    name: Generate ${{ env.build_name }}
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: ${{ env.checkout_ref }}
      scout_build_name: ${{ env.build_name }}
