name: Generate Production Build

on:
  workflow_dispatch:

jobs:
  call-workflow:
    name: Generate ProductionBuild
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      scout_checkout_ref: release
      scout_build_name: ProductionBuild
