name: Generate Production Build

on:
  workflow_dispatch:
    checkout_ref:
      description: 'Checkout branch, tag or SHA'
      required: true
      type: choice
      default: 'release'
      options:
      - release
      - main

jobs:
  call_workflow_job:
    needs: init_vars_job
    name: Generate ${{ needs.init_vars_job.outputs.scout_build_name }}
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/android-ci-workflow.yml
    with:
      build_name: 'ProductionBuild'
      checkout_ref: ${{ inputs.checkout_ref }}
