name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying affected apps
    steps:
      - uses: actions/checkout@v4
      - uses: PatrikValkovic/last-successful-commit-action@v3.1
        id: last_successful_commit
        with:
          branch: 'master'
          workflow_id: 'android.yml'
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          echo "commit id: ${{ steps.last_successful_commit.outputs.commit_hash }}"