name: NX sha examples

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build Name'
        required: false
        type: choice
        default: "EngineeringBuild"
        options:
        - "EngineeringBuild"
        - "QaBuild"
      checkout_ref:
        description: 'Checkout branch, tag or SHA'
        required: false
        type: string
        default: "main"        

permissions:
  actions: read
  contents: read
  
jobs:
  initJob:
    runs-on: ubuntu-latest
    name: Init Job
    steps:
      - run: |
          echo "build_name: ${{ inputs.build_name }}"
          echo "checkout_ref: ${{ inputs.checkout_ref }}"
          
  myJob:
    runs-on: ubuntu-latest
    name: My Job
    needs: initJob
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout_ref }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ steps.setSHAs.outputs.base }}"
          echo "HEAD: ${{ steps.setSHAs.outputs.head }}"
