name: simple-main-github-actions
run-name: ${{ github.actor }} is running simple main action
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print build environment
        run:
          env | sort 
