name: simple-release-github-actions
run-name: ${{ github.actor }} is running simple release action
on: 
  push:
    - 'main'
  workflow_dispatch:
jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print build environment
        run:
          env | sort 
