name: Test Copy From Ookla S3
on: 
  push:
    branches:
      - 'main'

env:
  FILE_NAME: 's3://ookla-android-maven-repo/release/com/ookla/speedtest/sdk/speedtest-sdk/2.5.3.8/speedtest-sdk-2.5.3.8.pom'

jobs:
  cp_from_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets. AWS_OOKLA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets. AWS_OOKLA_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: Test permission
        run:
          aws s3 cp ${{ env.FILE_NAME }} .
          
